import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart3, Bell, BellRing, CalendarDays, Check, ChevronLeft, ChevronRight, Circle, Clock3, Download, Flame, LayoutGrid, ListChecks, Pencil, Play, Plus, RotateCcw, Search, Settings2, Sparkles, Target, Trash2, Trophy, Upload, X, LogOut } from 'lucide-react';
import { LocalNotifications } from '@capacitor/local-notifications';
import './styles.css';
import './daily.css';

const STORAGE='taskflow-tasks-v5', PROFILE_STORAGE='taskflow-profile-v1', THEME_STORAGE='taskflow-theme-v2', GOALS_STORAGE='taskflow-goals-v1';
const TODAY=()=>new Date().toISOString().slice(0,10);
const DATE_KEY=d=>{const x=new Date(d);return new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const addDays=(s,n)=>{const d=new Date(`${s}T12:00:00`);d.setDate(d.getDate()+n);return DATE_KEY(d)};
const daysBetween=(a,b)=>Math.round((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/86400000);
const starterTasks=[
{id:'1',title:'Finish ML assignment',category:'Study',priority:'High',due:'Today',date:TODAY(),time:'19:30',repeat:'None',done:false,alarm:true,notes:''},
{id:'2',title:'Build the TaskFlow UI',category:'Work',priority:'Medium',due:'Today',date:TODAY(),time:'21:00',repeat:'None',done:false,alarm:false,notes:''},
{id:'3',title:'Read for 20 minutes',category:'Personal',priority:'Low',due:'Today',date:TODAY(),time:'22:15',repeat:'None',done:true,completedDates:[TODAY()],alarm:false,notes:''},
{id:'4',title:'Plan tomorrow',category:'Personal',priority:'Medium',due:'Tomorrow',date:addDays(TODAY(),1),time:'18:00',repeat:'None',done:false,alarm:false,notes:''}
];
const categories=['All','Study','Work','Personal'],priorities=['Low','Medium','High'],repeats=['None','Every day','Weekdays','Every week','Every 2 weeks','Every month'];
const readStorage=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}};
const normalizeTasks=raw=>(Array.isArray(raw)?raw:starterTasks).map(t=>({...t,date:t.date||TODAY(),alarm:!!t.alarm,notes:t.notes||'',completedDates:Array.isArray(t.completedDates)?t.completedDates:[]}));
const isRecurring=t=>t.repeat&&t.repeat!=='None';
const occursOn=(t,date)=>{if(!isRecurring(t))return(t.date||TODAY())===date;const start=t.date||TODAY(),diff=daysBetween(start,date);if(diff<0)return false;if(t.repeat==='Every day')return true;if(t.repeat==='Weekdays'){const d=new Date(`${date}T12:00:00`).getDay();return d>=1&&d<=5}if(t.repeat==='Every week')return diff%7===0;if(t.repeat==='Every 2 weeks')return diff%14===0;if(t.repeat==='Every month'){const a=new Date(`${start}T12:00:00`),b=new Date(`${date}T12:00:00`);return a.getDate()===b.getDate()}return false};
const doneOn=(t,date)=>isRecurring(t)?(t.completedDates||[]).includes(date):t.done;
const isOverdue=t=>!isRecurring(t)&&!doneOn(t,TODAY())&&(t.date||TODAY())<TODAY();

function App(){
 const [profile,setProfile]=useState(()=>readStorage(PROFILE_STORAGE,null)),[profileForm,setProfileForm]=useState({name:'',gender:''});
 const [tasks,setTasks]=useState(()=>normalizeTasks(readStorage(STORAGE,starterTasks))),[goals,setGoals]=useState(()=>readStorage(GOALS_STORAGE,[]));
 const [view,setView]=useState('tasks'),[tab,setTab]=useState('Today'),[category,setCategory]=useState('All'),[query,setQuery]=useState('');
 const [showAdd,setShowAdd]=useState(false),[editing,setEditing]=useState(null),[selectedDate,setSelectedDate]=useState(TODAY()),[calendarMonth,setCalendarMonth]=useState(new Date(`${TODAY()}T12:00:00`));
 const [notice,setNotice]=useState(''),[undoTask,setUndoTask]=useState(null),[focusMinutes,setFocusMinutes]=useState(25),[focusSeconds,setFocusSeconds]=useState(25*60),[focusRunning,setFocusRunning]=useState(false),[focusTask,setFocusTask]=useState('');
 const emptyTask={title:'',category:'Study',priority:'Medium',due:'Today',date:TODAY(),time:'',repeat:'None',alarm:false,notes:''};const [form,setForm]=useState(emptyTask);
 useEffect(()=>localStorage.setItem(STORAGE,JSON.stringify(tasks)),[tasks]);
 useEffect(()=>localStorage.setItem(GOALS_STORAGE,JSON.stringify(goals)),[goals]);
 useEffect(()=>{localStorage.setItem(THEME_STORAGE,JSON.stringify('light'));document.documentElement.dataset.theme='light';document.body.dataset.theme='light'},[]);
 useEffect(()=>{if(!focusRunning)return;const id=setInterval(()=>setFocusSeconds(s=>{if(s<=1){clearInterval(id);setFocusRunning(false);setFocusSeconds(focusMinutes*60);setNotice('Focus session complete!');return focusMinutes*60}return s-1}),1000);return()=>clearInterval(id)},[focusRunning,focusMinutes]);
 const todayTasks=tasks.filter(t=>occursOn(t,TODAY())),completed=todayTasks.filter(t=>doneOn(t,TODAY())).length,pending=todayTasks.length-completed,progress=todayTasks.length?Math.round(completed/todayTasks.length*100):0;
 const completedDates=[...new Set(tasks.flatMap(t=>t.completedDates||[]).concat(tasks.filter(t=>t.done&&t.date).map(t=>t.date)))];let streak=0;for(let i=0;;i++){if(completedDates.includes(addDays(TODAY(),-i)))streak++;else break}
 const weekStart=addDays(TODAY(),-6),weekDone=completedDates.filter(d=>d>=weekStart&&d<=TODAY()).length,overdue=tasks.filter(isOverdue),avg=Math.round(weekDone/7*10)/10;
 const categoryStats=categories.slice(1).map(c=>{const ts=tasks.filter(t=>t.category===c),done=ts.reduce((n,t)=>n+(t.completedDates?.length||0)+(t.done?1:0),0);return{c,pct:Math.min(100,Math.round(done/Math.max(ts.length,1)*100))}});
 const filtered=useMemo(()=>tasks.filter(t=>{const done=doneOn(t,TODAY());const match=tab==='Today'?occursOn(t,TODAY()):tab==='Daily'?isRecurring(t):tab==='Upcoming'?(!isRecurring(t)&&(t.date||TODAY())>TODAY()&&!done):done;return match&&(category==='All'||t.category===category)&&t.title.toLowerCase().includes(query.toLowerCase().trim())}),[tasks,tab,category,query]);
 const saveProfile=e=>{e.preventDefault();const name=profileForm.name.trim();if(!name||!profileForm.gender)return;const next={name,gender:profileForm.gender};localStorage.setItem(PROFILE_STORAGE,JSON.stringify(next));setProfile(next)};
 const logout=()=>{if(!confirm('Log out of TaskFlow? Your tasks will stay saved on this device.'))return;localStorage.removeItem(PROFILE_STORAGE);setProfile(null);setProfileForm({name:'',gender:''})};
 const toggle=id=>setTasks(ts=>ts.map(t=>{if(t.id!==id)return t;if(isRecurring(t)){const dates=new Set(t.completedDates||[]);dates.has(TODAY())?dates.delete(TODAY()):dates.add(TODAY());return{...t,completedDates:[...dates]}}return{...t,done:!t.done,completedDates:!t.done?[...(t.completedDates||[]),t.date||TODAY()]:t.completedDates||[]}}));
 const remove=id=>{const t=tasks.find(x=>x.id===id);setTasks(ts=>ts.filter(x=>x.id!==id));setUndoTask(t);setTimeout(()=>setUndoTask(null),5000)};const undo=()=>{if(undoTask){setTasks(ts=>[undoTask,...ts]);setUndoTask(null)}};
 const openEdit=t=>{setEditing(t.id);setForm({...emptyTask,...t});setShowAdd(true)};
 const scheduleAlarm=async t=>{try{const p=await LocalNotifications.requestPermissions();if(p.display!=='granted'){setNotice('Allow notifications to use alarms.');return}const d=new Date(`${t.date||TODAY()}T${t.time}:00`);if(d<=new Date()){setNotice('Choose a future time for the alarm.');return}await LocalNotifications.schedule({notifications:[{id:Math.floor(Math.random()*2000000000),title:'TaskFlow Alarm',body:t.title,schedule:{at:d,allowWhileIdle:true},sound:'default',extra:{taskId:t.id}}]});setNotice(`Alarm set for ${t.time}.`)}catch{setNotice('Alarms work in the Android app after Local Notifications are synced.')}};
 const saveTask=e=>{e.preventDefault();if(!form.title.trim())return;const old=tasks.find(t=>t.id===editing),data={...form,title:form.title.trim(),id:editing||crypto.randomUUID?.()||String(Date.now()),done:old?.done||false,completedDates:old?.completedDates||[]};setTasks(ts=>editing?ts.map(t=>t.id===editing?data:t):[data,...ts]);setShowAdd(false);setEditing(null);setForm(emptyTask);setTab(data.repeat!=='None'?'Daily':data.due==='Today'?'Today':'Upcoming');if(data.alarm&&data.time)scheduleAlarm(data)};
 const requestNotifications=async()=>{try{const p=await LocalNotifications.requestPermissions();setNotice(p.display==='granted'?'Notifications enabled.':'Notifications were not enabled.')}catch{setNotice('Install the Android build to use native notifications and alarms.')}};
 const exportData=()=>{const blob=new Blob([JSON.stringify({version:5,exportedAt:new Date().toISOString(),profile,tasks,goals},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`taskflow-backup-${TODAY()}.json`;a.click();setNotice('Backup exported.')};
 const importData=e=>{const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.tasks))throw Error();setTasks(normalizeTasks(d.tasks));if(d.profile){setProfile(d.profile);localStorage.setItem(PROFILE_STORAGE,JSON.stringify(d.profile))}if(Array.isArray(d.goals))setGoals(d.goals);setNotice('Backup restored.')}catch{setNotice('Invalid TaskFlow backup.')}};r.readAsText(file);e.target.value=''};
 const calendarDays=()=>{const y=calendarMonth.getFullYear(),m=calendarMonth.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),arr=[];for(let i=0;i<start;i++)arr.push(null);for(let d=1;d<=days;d++)arr.push(DATE_KEY(new Date(y,m,d)));return arr};
 const monthLabel=calendarMonth.toLocaleDateString('en-IN',{month:'long',year:'numeric'}),dayTasks=tasks.filter(t=>occursOn(t,selectedDate)),goalDone=completedDates.length,formatFocus=()=>`${String(Math.floor(focusSeconds/60)).padStart(2,'0')}:${String(focusSeconds%60).padStart(2,'0')}`;
 const setCustomFocus=value=>{const n=Math.max(1,Math.min(180,Number(value)||1));setFocusRunning(false);setFocusMinutes(n);setFocusSeconds(n*60)};
 if(!profile)return <div className="app-shell onboarding"><div className="glow glow-one"/><div className="glow glow-two"/><main className="onboarding-card"><span className="eyebrow"><Sparkles size={13}/> TASKFLOW</span><h1>Welcome to TaskFlow<span>.</span></h1><p>Let's keep things simple. Tell us a little about you.</p><form onSubmit={saveProfile}><label>Your name</label><input autoFocus value={profileForm.name} onChange={e=>setProfileForm({...profileForm,name:e.target.value})} placeholder="Enter your name" maxLength={30}/><label>Gender</label><div className="gender-row">{['Male','Female','Other'].map(g=><button type="button" className={profileForm.gender===g?'gender active':'gender'} onClick={()=>setProfileForm({...profileForm,gender:g})} key={g}>{g}</button>)}</div><button className="create" disabled={!profileForm.name.trim()||!profileForm.gender}>Continue <ChevronRight size={18}/></button></form><small>Your information stays on this device.</small></main></div>;
 return <div className="app-shell"><div className="glow glow-one"/><div className="glow glow-two"/><main className="phone">
 <header className="topbar"><div><span className="eyebrow"><Sparkles size={13}/> TASKFLOW</span><h1>Good evening, {profile.name}<span>.</span></h1><p>{new Intl.DateTimeFormat('en-IN',{weekday:'long',month:'long',day:'numeric'}).format(new Date())} · Keep your momentum going.</p></div></header>
 {view==='tasks'&&<><section className="hero-card"><div><div className="hero-label">TODAY'S FOCUS</div><strong>{pending} <small>tasks remaining</small></strong><p>{pending?'One task at a time. You’ve got this.':'Everything is under control.'}</p></div><div className="ring" style={{'--progress':`${progress*3.6}deg`}}><div><b>{progress}%</b><span>done</span></div></div></section><div className="quick-stats"><div><Flame size={16}/><b>{streak}</b><span>day streak</span></div><div><Target size={16}/><b>{completed}</b><span>completed</span></div><div><Clock3 size={16}/><b>{overdue.length}</b><span>overdue</span></div></div><div className="section-head"><div><span>YOUR TASKS</span><h2>{tab}</h2></div><button className="add-btn" onClick={()=>{setEditing(null);setForm(emptyTask);setShowAdd(true)}}><Plus size={19}/><span>Add task</span></button></div><div className="tabs">{['Today','Daily','Upcoming','Done'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="filter-row"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks"/></div><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></div><div className="task-list">{filtered.length?filtered.map(t=><article className={`task ${doneOn(t,TODAY())?'done':''} ${isOverdue(t)?'overdue':''}`} key={t.id}><button className={`check ${doneOn(t,TODAY())?'checked':''}`} onClick={()=>toggle(t.id)}>{doneOn(t,TODAY())?<Check size={17}/>:<Circle size={19}/>}</button><div className="task-main"><h3>{t.title}</h3><div className="meta"><span className={`tag ${t.category.toLowerCase()}`}>{t.category}</span><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</span>{isOverdue(t)&&<span className="overdue-badge">OVERDUE</span>}{isRecurring(t)&&<span className="repeat-badge">↻ {t.repeat}</span>}{t.alarm&&<span className="alarm-badge"><BellRing size={10}/> Alarm</span>}{t.time&&<span className="time"><Clock3 size={11}/> {t.time}</span>}</div></div><button className="edit" onClick={()=>openEdit(t)}><Pencil size={15}/></button><button className="delete" onClick={()=>remove(t.id)}><Trash2 size={16}/></button></article>):<div className="empty"><ListChecks size={30}/><h3>Nothing here yet</h3><p>Tap “Add task” and make your next move.</p></div>}</div></>}
 {view==='calendar'&&<section className="page-card calendar-page"><span className="eyebrow"><CalendarDays size={13}/> CALENDAR</span><div className="calendar-head"><button className="icon-btn" onClick={()=>setCalendarMonth(new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()-1,1))}><ChevronLeft size={17}/></button><h2>{monthLabel}</h2><button className="icon-btn" onClick={()=>setCalendarMonth(new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+1,1))}><ChevronRight size={17}/></button></div><div className="weekdays">{['M','T','W','T','F','S','S'].map((x,i)=><span key={i}>{x}</span>)}</div><div className="calendar-grid">{calendarDays().map((d,i)=><button disabled={!d} className={`${d===selectedDate?'selected':''} ${d===TODAY()?'today':''} ${d&&tasks.some(t=>occursOn(t,d))?'has-task':''}`} onClick={()=>d&&setSelectedDate(d)} key={i}>{d?Number(d.slice(-2)):''}</button>)}</div><div className="calendar-tasks"><h3>{new Date(`${selectedDate}T12:00:00`).toLocaleDateString('en-IN',{weekday:'long',month:'long',day:'numeric'})}</h3>{dayTasks.length?dayTasks.map(t=><div className="mini-task" key={t.id}><span className={doneOn(t,selectedDate)?'mini-check done':'mini-check'}>{doneOn(t,selectedDate)?'✓':'○'}</span><div><b>{t.title}</b><small>{t.time||'No time'} · {t.category}</small></div></div>):<p className="muted">No tasks scheduled.</p>}</div></section>}
 {view==='tools'&&<section className="page-card"><span className="eyebrow"><Target size={13}/> PRODUCTIVITY TOOLS</span><h2>Work smarter</h2><p className="muted">Focus sessions and goals to keep your momentum moving.</p><div className="tool-cards"><button className="tool-card" onClick={()=>setView('focus')}><span className="tool-icon"><Clock3 size={21}/></span><div><b>Focus Timer</b><span>Build deep-work sessions with your own duration.</span></div><span className="tool-arrow"><ChevronRight size={18}/></span></button><button className="tool-card" onClick={()=>setView('goals')}><span className="tool-icon"><Trophy size={21}/></span><div><b>Goals</b><span>Track milestones and completion targets.</span></div><span className="tool-arrow"><ChevronRight size={18}/></span></button></div></section>}
 {view==='insights'&&<section className="page-card"><span className="eyebrow"><BarChart3 size={13}/> INSIGHTS</span><h2>Your productivity</h2><p className="muted">A clearer picture of your week.</p><div className="insight-grid"><div><span>Completion</span><strong>{progress}%</strong></div><div><span>Done this week</span><strong>{weekDone}</strong></div><div><span>Overdue</span><strong>{overdue.length}</strong></div><div><span>Streak</span><strong>{streak}d</strong></div></div><h3 className="subhead">Categories</h3><div className="category-bars">{categoryStats.map(s=><div key={s.c}><div><span>{s.c}</span><b>{s.pct}%</b></div><div className="bar"><span style={{width:`${s.pct}%`}}/></div></div>)}</div><h3 className="subhead">This week</h3><div className="week-summary"><div><b>{weekDone}</b><span>completed</span></div><div><b>{avg}</b><span>avg/day</span></div><div><b>{overdue.length}</b><span>overdue</span></div></div></section>}
 {view==='goals'&&<section className="page-card"><span className="eyebrow"><Trophy size={13}/> GOALS</span><h2>Your goals</h2><p className="muted">Turn completed tasks into progress.</p><div className="goal-list">{goals.map(g=>{const current=goalDone,pct=Math.min(100,Math.round(current/g.target*100));return <div className="goal-card" key={g.id}><div className="goal-top"><div><b>{g.title}</b><span>{current} / {g.target}</span></div><strong>{pct}%</strong></div><div className="bar"><span style={{width:`${pct}%`}}/></div></div>})}</div><button className="create goal-add" onClick={()=>{const title=prompt('Goal name?');const target=Number(prompt('Target number of completed task dates?'));if(title&&target>0)setGoals(gs=>[...gs,{id:crypto.randomUUID?.()||String(Date.now()),title,target}])}}><Plus size={17}/> Add goal</button><div className="goal-note"><Target size={18}/><span>{goalDone} total completion dates recorded.</span></div></section>}
 {view==='focus'&&<section className="page-card focus-page"><span className="eyebrow"><Clock3 size={13}/> FOCUS TIMER</span><h2>Deep work</h2><p className="muted">Choose a duration that fits your work session.</p><div className="focus-clock">{formatFocus()}</div><select value={focusTask} onChange={e=>setFocusTask(e.target.value)}><option value="">No task selected</option>{tasks.filter(t=>!doneOn(t,TODAY())).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><div className="focus-controls"><button onClick={()=>setFocusRunning(v=>!v)}>{focusRunning?'Pause':<><Play size={17}/> Start</>}</button><button onClick={()=>{setFocusRunning(false);setFocusSeconds(focusMinutes*60)}}><RotateCcw size={17}/> Reset</button></div><div className="focus-presets">{[15,25,45].map(m=><button className={focusMinutes===m&&!focusRunning?'active':''} onClick={()=>setCustomFocus(m)} key={m}>{m} min</button>)}</div><div className="custom-focus"><label>Custom duration</label><div><input type="number" min="1" max="180" value={focusMinutes} disabled={focusRunning} onChange={e=>setCustomFocus(e.target.value)}/><span>minutes</span></div><small>Set any duration from 1 to 180 minutes.</small></div></section>}
 {view==='settings'&&<section className="page-card"><span className="eyebrow"><Settings2 size={13}/> SETTINGS</span><h2>Make TaskFlow yours</h2><div className="setting-row"><div><b>Profile</b><span>{profile.name} · {profile.gender}</span></div></div><div className="setting-row"><div><b>Notifications & alarms</b><span>Schedule Android reminders.</span></div><button className="setting-toggle" onClick={requestNotifications}><Bell size={14}/> Enable</button></div><div className="setting-row"><div><b>Local storage</b><span>Your tasks stay on this device.</span></div><span className="status-dot">Local</span></div><div className="backup-actions"><button onClick={exportData}><Download size={15}/> Export backup</button><label><Upload size={15}/> Restore backup<input type="file" accept="application/json" onChange={importData}/></label></div><div className="about"><Sparkles size={18}/><div><b>TaskFlow by Maha</b><p>Offline-first personal productivity.</p></div></div><button className="danger" onClick={()=>{if(confirm('Reset all tasks?'))setTasks(starterTasks)}}>Reset demo tasks</button><button className="logout-btn" onClick={logout}><LogOut size={16}/> Log out</button></section>}
 <nav className="bottom-nav"><button className={view==='tasks'?'selected':''} onClick={()=>setView('tasks')}><LayoutGrid size={18}/><span>Tasks</span></button><button className={view==='calendar'?'selected':''} onClick={()=>setView('calendar')}><CalendarDays size={18}/><span>Calendar</span></button><button className={view==='tools'||view==='focus'||view==='goals'?'selected':''} onClick={()=>setView('tools')}><Target size={18}/><span>Tools</span></button><button className={view==='insights'?'selected':''} onClick={()=>setView('insights')}><BarChart3 size={18}/><span>Insights</span></button><button className={view==='settings'?'selected':''} onClick={()=>setView('settings')}><Settings2 size={18}/><span>Settings</span></button></nav><footer>Designed & developed by <b>Maha</b></footer>
 </main>{notice&&<div className="toast" onClick={()=>setNotice('')}>{notice}</div>}{undoTask&&<div className="undo-toast">Task deleted <button onClick={undo}>UNDO</button></div>}
 {showAdd&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&(setShowAdd(false),setEditing(null))}><form className="sheet" onSubmit={saveTask}><div className="sheet-head"><div><span className="eyebrow">{editing?'EDIT TASK':'NEW TASK'}</span><h2>{editing?'Edit task':'What’s next?'}</h2></div><button type="button" className="icon-btn" onClick={()=>{setShowAdd(false);setEditing(null)}}><X size={18}/></button></div><input autoFocus className="task-input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Study for 30 minutes" maxLength={100}/><div className="field"><label>Category</label><div className="choice-row">{categories.slice(1).map(x=><button type="button" className={form.category===x?'choice active':'choice'} onClick={()=>setForm({...form,category:x})} key={x}>{x}</button>)}</div></div><div className="field"><label>Priority</label><div className="choice-row">{priorities.map(x=><button type="button" className={form.priority===x?'choice active':'choice'} onClick={()=>setForm({...form,priority:x})} key={x}>{x}</button>)}</div></div><div className="field"><label>Repeat</label><div className="choice-row repeat-options">{repeats.map(x=><button type="button" className={form.repeat===x?'choice active':'choice'} onClick={()=>setForm({...form,repeat:x})} key={x}>{x}</button>)}</div></div><div className="form-row"><div className="field"><label>Due</label><select value={form.due} onChange={e=>setForm({...form,due:e.target.value,date:e.target.value==='Today'?TODAY():e.target.value==='Tomorrow'?addDays(TODAY(),1):form.date})}><option>Today</option><option>Tomorrow</option><option>Later</option></select></div><div className="field"><label>Date</label><input type="date" value={form.date||TODAY()} onChange={e=>setForm({...form,date:e.target.value,due:e.target.value===TODAY()?'Today':e.target.value===addDays(TODAY(),1)?'Tomorrow':'Later'})}/></div></div><div className="form-row"><div className="field"><label>Time</label><input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></div><div className="field"><label>Alarm</label><button type="button" className={form.alarm?'alarm-toggle active':'alarm-toggle'} onClick={()=>setForm({...form,alarm:!form.alarm})}><BellRing size={15}/>{form.alarm?'Alarm on':'Set alarm'}</button></div></div><div className="field"><label>Notes</label><textarea className="task-notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Optional notes..." maxLength={500}/></div><button className="create" type="submit">{editing?'Save changes':'Create task'} <ChevronRight size={18}/></button></form></div>}
 </div>}

createRoot(document.getElementById('root')).render(<App/>);
